@Library('github.com/sanmechie/JenkinsSharedPipeline')_

param_pipeline OS:genRandom()



def genRandom(){
    int x = Random.nextInt(10)
    if (x < 5) {
        return 'true'
    } else{
        return 'false'
    }
}