@Library('github.com/sanmechie/JenkinsSharedPipeline')_

param_pipeline OS:genRandom()





def genRandom(){
    Random rnd = new Random()
    int x = rnd.nextInt(10)
    if (x < 5) {
        return 'true'
    } else{
        return 'false'
    }
}