@Library('github.com/sanmechie/JenkinsSharedPipeline')_

param_pipeline OS:genRandom()



Random rnd = new Random()

def genRandom(){
    int x = rnd.nextInt(10)
    if (x < 5) {
        return 'true'
    } else{
        return 'false'
    }
}