pipeline {
    agent any
    environment {
        RELEASE = 'PROD'
    }

    stages {
        stage('Build'){
         environment {
             STAGE_NAME = 'BUILD'
         }
         steps {
           echo "This is stage ${STAGE_NAME} and release is ${env.RELEASE}"

         }


        }
        stage('Test'){
            steps {
                echo "This is release $RELEASE"
            }
        }

        stage('Deploy'){
            input {
                message 'Deploy?'
                ok 'Do it!'
                parameters {
                    string(name: 'TARGET_ENV', defaultValue: 'QA', description:'This is QA env')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} in environment ${TARGET_ENV}"
            }
        }

        stage ('write text'){
            steps{
                echo 'Writing to text file'
                writeFile file: 'test-results.txt', text: 'Passed'
            }
        }

        stage('Parallel block') {
          parallel{
           stage('Stage1'){
               steps{
                   script {
                       for(int i=0; i < 1000; i++){
                           echo "Iterating  for $i"
                           test(i)

                       }

                   }
               }
           }

              stage('Stage2'){
               steps{
                   script {
                       for(int i=0; i < 1000; i++){
                           echo "Iterating  for $i"
                           test(i)

                       }

                   }
               }
           }

          }



        }



    }

    post {
        always {
            echo 'Print irrpestive of build success  or fail'
            
        }
        success {
            archiveArtifacts 'test-results.txt'
        }
    }
}


def test(var) {
    println(var)
}